# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa600e3e65eca29269a3774af617442164fb8765fea5541cdb9733412a45d4a9ea1b326a732f6749fecf3094836ba43508928ca082734d3374d744f6d23604f9

test:
  secret_key_base: 1e035861194f4e2746423c0462f32a141105e3c48d5617155f523c20a37d2fdf8c57ca0ff1d38e35a72bc39a148d30ba3725d7b914fa1a4c0ff1f1c1e0beb074

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
