# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 77efeda95b9ebec1b199656cf01c78d55510f168c1248cc3d9937633c19cf81c26d64430fcecee25d51a5dd92623c59945563853a45c2f43f18973aea4f8f15c

test:
  secret_key_base: d94ebb1e5eac178bd8123031a52f7b1a703c0522ad9bff50ee217b4c9f4b4d47014c523262ef61f474446028cbe3bc01b550adfffe08849bb1622b35130a4fd8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
