# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f335741c6b40c72fca3aed322d31650961f6a665e0c758a3d5848d17ae4da537455a5943ec3c53a6789dba243e35502c5e96aabc76b71876f52480f1d3dbd489

test:
  secret_key_base: e67935e1e8ac051fabc6879c4c211a23cf746931b52575592339def0849a8f003ae28b0326ad78753ba4d2047620b36aadf171aa76efcf81b979c4764d395e6e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
